# Generated by Django 6.1.1 on 2026-10-06 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('plot', models.TextField(blank=True)),
                ('release_date', models.CharField(blank=True, max_length=50)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('directors', models.JSONField(blank=True, default=list)),
                ('writers', models.JSONField(blank=True, default=list)),
                ('stars', models.JSONField(blank=True, default=list)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('watched_date', models.DateField(blank=True, null=True)),
                ('opinion', models.TextField(blank=True)),
                ('favourite_quotes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'imdb_id')},
            },
        ),
    ]
