# Generated by Django 6.1.1 on 2026-10-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usermovie_favourite_scene_url_alter_usermovie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovie',
            name='taglines',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
